// Fictional sample letters so visitors can try ClearRights without their own.
// Same text as demo/*.txt.

export const SAMPLES = {
  deposit: "Eksempel Utleie AS\nPostboks 123, 5804 Bergen\n\nBergen, 18. september 2026\n\nTil: Ayse Yilmaz\nNygårdsgaten 12, leilighet H0203\n5015 Bergen\n\nVedrørende: Krav om dekning fra depositum – leieforhold Nygårdsgaten 12, leilighet H0203\n\nLeieforholdet ble avsluttet 31. august 2026. Ved utflyttingsbefaringen 1. september 2026 ble det registrert skader på parkettgulvet i stuen, samt at kjøkken og bad ikke var tilstrekkelig rengjort.\n\nUtleier krever derfor at kr 8 500 av depositumet dekkes, fordelt slik:\n- Reparasjon av parkett i stue: kr 6 000\n- Rengjøring av kjøkken og bad: kr 2 500\n\nResten av depositumet, kr 16 500, vil bli utbetalt til din konto innen 5. oktober 2026.\n\nDersom du er uenig i kravet, må du gi skriftlig tilbakemelding innen 14 dager fra mottak av dette brevet. Dersom vi ikke mottar innsigelse innen fristen, vil vi anse kravet som godtatt og be banken om å utbetale kr 8 500 fra depositumskontoen til utleier.\n\nBilder fra utflyttingsbefaringen kan fås ved henvendelse til oss.\n\nMed vennlig hilsen\nEksempel Utleie AS\nKari Nordmann\nForvalter",
  debt: "Eksempel Inkasso AS\nPostboks 456 Sentrum, 5808 Bergen\nTelefon 55 00 00 00 – post@eksempel-inkasso.no\n\nBergen, 21. september 2026\n\nAyse Yilmaz\nNygårdsgaten 12\n5015 Bergen\n\nBETALINGSOPPFORDRING\n\nVår referanse: 2026-448120\nOppdragsgiver: Eksempel Mobil AS\nKundenummer hos oppdragsgiver: 7730215\n\nVi har fått i oppdrag å kreve inn følgende ubetalte krav:\n\nFaktura nr. 55102, forfall 10. august 2026\nHovedstol:                     kr 1 249,00\nForsinkelsesrente:             kr    21,30\nInkassosalær og gebyrer:       kr   140,00\nTotalt å betale:               kr 1 410,30\n\nBeløpet må betales innen 14 dager fra dette brevets dato til kontonummer 1234.56.78901. Merk betalingen med referanse 2026-448120.\n\nDersom beløpet ikke er betalt innen fristen, vil saken kunne bli sendt til rettslig inkasso. Dette vil medføre ytterligere kostnader for deg, og kan føre til betalingsanmerkning.\n\nHar du innsigelser mot kravet, må du gi oss beskjed skriftlig før betalingsfristen går ut. Kravet vil da bli stilt i bero mens innsigelsen behandles.\n\nDersom du ikke har mulighet til å betale hele beløpet, kan du kontakte oss for å avtale en nedbetalingsplan.\n\nMed vennlig hilsen\nEksempel Inkasso AS\nSaksbehandler: Ola Hansen",
};

export type SampleId = keyof typeof SAMPLES;
